- name: Install Docker community version
  become: yes
  package:
      name: docker-ce
      state: present

- name: Start Docker service
  become: yes
  service:
      name: docker
      state: started
